name: "Create API CI"

on: 
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - '*'

jobs:
  macos-run-tests:
    name: Unit Tests (macOS, Xcode 13.0)
    runs-on: macOS-11
    env:
      DEVELOPER_DIR: /Applications/Xcode_13.0.app/Contents/Developer
    steps:
      - uses: actions/checkout@v2
      - name: Run Tests
        run: swift test
  macos-compile-generated-code:
    name: Unit Tests (macOS, Xcode 13.0)
    runs-on: macOS-11
    env:
      DEVELOPER_DIR: /Applications/Xcode_13.0.app/Contents/Developer
    steps:
      - uses: actions/checkout@v2
      - name: Compile Generated Code
        run: ./Scripts/test-generated.sh
